apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: myapp
    type: frontend
spec:
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        tier: frontend
        teste: chamaaaaaaaaaa
    spec:
      containers:
      - name: nginx
        image: nginx
  replicas: 3