apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-myreplicaset
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      name: nginx-3
      labels:
        env: dev
    spec:
      containers:
        - name: nginx-3
          image: nginx
