apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-rs
  labels:
    app: myapp
    type: frontend
spec:
  template:
    metadata:
      name: nginx-rs
      labels:
        app: nginx
        type: frontend
        teste: chamaaaaaaaaaa
    spec:
      containers:
      - name: nginx-rs
        image: nginx
  replicas: 3
  selector:
    matchLabels:
      type: frontend