apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app
  labels:
    app: result-app
spec:
  replicas: 1
  template:
    metadata:
      name: result-app
      labels:
        app: result-app
    spec:
      containers:
      - name: result-app
        image: dockersamples/examplevotingapp_result
        #image: kodekloud/examplevotingapp_result:v1
        ports:
          - containerPort: 80
            name: result
  selector:
    matchLabels:
      app: result-app