apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  type: ClusterIP #default
  ports:
  - name: "postgres-service"
    port: 5432
    targetPort: 5432
  selector:
    app: postgres