apiVersion: v1
kind: Service
metadata:
  name: result-app
  labels:
    app: result-app
spec:
  type: NodePort
  ports:
  - name: "result-app-service"
    port: 8081
    targetPort: 80
    nodePort: 31001
  selector:
    app: result-app