apiVersion: v1
kind: Service
metadata:
  name: voting-app
  labels:
    app: voting-app
spec:
  type: NodePort
  ports:
  - name: "voting-app-service"
    port: 8080
    targetPort: 80
    nodePort: 31000
  selector:
    app: voting-app