apiVersion: v1
kind: Pod
metadata:
  name: result-app
  labels:
    app: result-app
spec:
  containers:
  - name: result-app
    image: dockersamples/examplevotingapp_result
    #image: kodekloud/examplevotingapp_result:v1
    ports:
      - containerPort: 80
        name: result